### ISSUE TITLE
_loadSource isn't called in IE9 when data-media attribute is present

### ISSUE THREAD

**Issue by ryanbagwell** [matthewwithanm/jquery.picplus#31]
https://github.com/matthewwithanm/jquery.picplus/blob/master/jquery.picplus.js#L174

In IE9, the above line prevents calling _loadSource when a source element has a data-media attribute.

If a media query is specified, it should load, right?

```
if (media || (window.matchMedia && mql.matches)) {
  ...
}
```

This works in everything except IE9 (I think) because all other browsers support window.matchMedia

**Comment by ryanbagwell** [comment]
nix that solution, I see what's happening. The problem still remains though. It looks we need a cross-browser replacement for window.matchMedia

**Comment by matthewwithanm** [comment]
In browsers that don't support matchMedia, it should fall back to the first source without a `data-media` attribute, so I think this is working as expected? If you need to support media query matching for those browsers, you should just be able to include a [matchMedia pollyfill](https://github.com/paulirish/matchMedia.js/) in your project.

**Comment by ryanbagwell** [comment]
Yes, adding that pollyfill was how I fixed it in IE9. Should we add that to the docs?

**Comment by matthewwithanm** [comment]
Yeah, definitely. PR? (:
